config/routes.rb
ComingSoon::Application.routes.draw do
  root :to => "SignUps#new"
    
  controller :sessions do 
	get 'login' => :new 
	post 'login' => :create 
	delete 'logout' => :destroy 
  end 

  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"
  
  resources :admins

  resources :sign_ups do
    member do
	  get :notify_alpha
	end
  end
  
  match "thanks" => "signUp#thanks"
     
  match "alpha_sent" => "signUp#alpha_sent"

end

app/models/admin.rb
require 'digest/sha2'

class Admin < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true
 
  validates :password, :presence => true, :confirmation => true
  attr_accessor :password_confirmation
  attr_reader   :password

  validate  :password_must_be_present
  
  def Admin.authenticate(name, password)
    if admin = find_by_name(name)
      if admin.hashed_password == encrypt_password(password, admin.salt)
        admin
      end
    end
  end

  def Admin.encrypt_password(password, salt)
    Digest::SHA2.hexdigest(password + "flickme" + salt)
  end
  
  # 'password' is a virtual attribute
  def password=(password)
    @password = password

    if password.present?
      generate_salt
      self.hashed_password = self.class.encrypt_password(password, salt)
    end
  end
  
  after_destroy :ensure_an_admin_remains

  def ensure_an_admin_remains
    if Admin.count.zero?
      raise "Can't delete last admin"
    end
  end     

  private

    def password_must_be_present
      errors.add(:password, "Missing password") unless hashed_password.present?
    end
  
    def generate_salt
      self.salt = self.object_id.to_s + rand.to_s
    end
end

app/models/sign_up.rb
class SignUp < ActiveRecord::Base
  validates :email, :presence => true,
					:uniqueness => true, 
                    :length => { :within => 5..50 }, 
                    :format => { :with => /^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/i }
  
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController  
  skip_before_filter :authorize, :only => [:new, :create]
  
  # GET /admins
  # GET /admins.xml
  def index
    @admins = Admin.order(:name)
	@total_sign_ups= SignUp.count
	
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @admins }
    end
  end

  # GET /admins/1
  # GET /admins/1.xml
  def show
    @admin = Admin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @admin }
    end
  end

  # GET /admins/new
  # GET /admins/new.xml
  def new
    @admin = Admin.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @admin }
    end
  end

  # GET /admins/1/edit
  def edit
    @admin = Admin.find(params[:id])
  end

  # POST /admins
  # POST /admins.xml
  def create
    @admin = Admin.new(params[:admin])

    respond_to do |format|
      if @admin.save
        format.html { redirect_to(admins_url, :notice => "Admin #{@admin.name} was successfully created.") }
        format.xml  { render :xml => @admin, :status => :created, :location => @admin }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @admin.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /admins/1
  # PUT /admins/1.xml
  def update
    @admin = Admin.find(params[:id])

    respond_to do |format|
      if @admin.update_attributes(params[:admin])
        format.html { redirect_to(admins_url, :notice => "Admin #{@admin.name} was successfully updated.") }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @admin.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /admins/1
  # DELETE /admins/1.xml
  def destroy
    @admin = Admin.find(params[:id])
    begin
      @admin.destroy
      flash[:notice] = "Admin #{@admin.name} deleted"
    rescue Exception => e
      flash[:notice] = e.message
    end

    respond_to do |format|
      format.html { redirect_to(admins_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authorize
  protect_from_forgery
  helper_method :current_admin
  
  protected

    def authorize
      unless Admin.find_by_id(session[:admin_id])
        redirect_to login_url, :notice => "Please log in"
      end
    end

  private
  
	def current_admin
	  @current_admin ||= Admin.find_by_id(session[:admin_id]) if session[:admin_id]
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authorize
    
  def new
    #flash.now[:alert] = "Here"
  end

  def create
    if admin = Admin.authenticate(params[:name], params[:password]) 
	  session[:admin_id] = admin.id 
	  redirect_to sign_ups_url, :notice => "Logged in successfully" 
	else 
	  flash.now[:alert] = "Invalid user/password combination"
	  render :action => 'new'
	end 
  end

  def destroy
	#session[:admin_id] = nil 
	reset_session
	redirect_to root_path, :notice => "Logged out" 
  end

end

app/controllers/sign_ups_controller.rb
class SignUpsController < ApplicationController
  skip_before_filter :authorize, :only => [ :new, :create, :thanks ]
  
  # GET /sign_ups
  # GET /sign_ups.xml
  def index
    @sign_ups = SignUp.all
	@referer = request.env['HTTP_REFERER']
  end

  # GET /sign_ups/new
  # GET /sign_ups/new.xml
  def new
    @sign_up = SignUp.new
  end

  # POST /sign_ups
  # POST /sign_ups.xml
  def create
    @sign_up = SignUp.new(params[:sign_up])
	@referer ||= request.env['HTTP_REFERER']
	@sign_up.ip_address = request.remote_ip
    @sign_up.user_agent = request.env['HTTP_USER_AGENT']
    @sign_up.referer = @referer

    respond_to do |format|
      if @sign_up.save
        format.html { render :action => "thanks", :notice => 'Sign up was successful.' }
        #redirect_to :thanks
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @sign_up.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def thanks
  end

  def alpha_sent
  end
  
  # DELETE /sign_ups/1
  # DELETE /sign_ups/1.xml
  def destroy
    @sign_up = SignUp.find(params[:id])
    @sign_up.destroy

    respond_to do |format|
      format.html { redirect_to(sign_ups_url) }
      format.xml  { head :ok }
    end
  end
  
  def notify?
    @sign_up = SignUp.find(params[:id])
	return @sign_up.notified==0
  end
  
  def notify_alpha
    @sign_up = SignUp.find(params[:id])
	
	Notifier.email_alpha(@sign_up).deliver
    
	#Assumming email was successfully sent so can update user state
	@sign_up.notified = 1

	respond_to do |format|
      if @sign_up.save
	    format.html { render :action => "alpha_sent", :notice => "Successfully sent notice to alpha user" }
        format.xml  { head :ok }
	  else
        format.html { render :action => "new" }
        format.xml  { render :xml => @sign_up.errors, :status => :unprocessable_entity }
      end
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sign_ups_helper.rb
module SignUpsHelper
end

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <fieldset> 
  <legend>Enter Admin Details</legend> 

  <div>
    <%= f.label :name %>:
    <%= f.text_field :name, :size => 40 %>
  </div>

  <div>
    <%= f.label :password, 'Password' %>:
    <%= f.password_field :password, :size => 40 %>
  </div>

  <div>
    <%= f.label :password_confirmation, 'Confirm' %>:
    <%= f.password_field :password_confirmation, :size => 40 %>
  </div>

  <div>
    <%= f.submit %>
  </div>

  </fieldset>
<% end %>

</div>

app/views/admins/edit.html.erb
<h1>Editing admin</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<h1>Listing Admins</h1>

It's <%= Time.now %> We have <%= pluralize(@total_sign_ups, "alpha request") %>.

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admins.each do |admin| %>
  <tr>
    <td><%= admin.name %></td>
    <td><%= link_to 'Show', admin %></td>
    <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
    <td><%= link_to 'Destroy', admin, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Admin', new_admin_path %>

app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<p>
  <b>Name:</b>
  <%= @admin.name %>
</p>

<p>
  <b>Hashed password:</b>
  <%= @admin.hashed_password %>
</p>

<p>
  <b>Salt:</b>
  <%= @admin.salt %>
</p>


<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coming Soon</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<div id="admin_nav">
  <% if current_admin %>
    Logged in as  <%= current_admin.name %>.
    <%= link_to "Log out", logout_path %>
  <% else %>
    <%= link_to "Admin Sign up", new_admin_path %> or
	<%= link_to "log in", login_path %>
  <% end %>
</div>

<%= content_tag :p, notice, :class => 'notice' if notice.present? %>
<%= content_tag :p, alert, :class => 'alert' if alert.present? %>

<%= yield %>

</body>
</html>

app/views/notifier/email_alpha.text.erb
<%= @greeting %>, Please join us in trying out the new FlickMe by going to <%= url_for("http://www.flickme.com") %>

app/views/sign_ups/_form.html.erb
<%= form_for(@sign_up) do |f| %>
  <% if @sign_up.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sign_up.errors.count, "error") %> prohibited this sign_up from being saved:</h2>

      <ul>
      <% @sign_up.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit "Notify Me" %>
  </div>
<% end %>

app/views/sign_ups/alpha_sent.html.erb
<div id="alpha_sent">Invitation to alpha sent.</div

<%= link_to 'Back', sign_ups_path %>

app/views/sign_ups/index.html.erb
<h1>Sign ups for flickme alpha</h1>

<table>
  <tr>
    <th>Email</th>
    <th>IP Address</th>
    <th>Browser</th>
    <th>Referer</th>
	<th>Sign Up Date</th>
	<th></th>
    <th></th>
    <th></th>
  </tr>

<% @sign_ups.each do |sign_up| %>
  <tr>
    <td><%= sign_up.email %></td>
    <td><%= sign_up.ip_address %></td>
	<td><%= sign_up.user_agent %></td>
    <td><%= sign_up.referer %></td>
    <td><%= sign_up.created_at %></td>		
	<td><%= link_to_if sign_up.notified.nil?, "Notify", notify_alpha_sign_up_path(sign_up) %></td>
    <td><%= link_to 'Destroy', sign_up, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/sign_ups/new.html.erb
<h1>Sign up for flickme alpha</h1>

<%= render 'form' %>

app/views/sign_ups/thanks.html.erb
<div id="thanks">Thanks for signing up. We'll contact you soon!</div>

<%= link_to 'New Sign up', new_sign_up_path %>